# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Identifier')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifier')),
                ('operation_date', models.DateField(verbose_name='Operation Date')),
                ('input_date', models.DateField(auto_now_add=True, verbose_name='Input Date')),
                ('label', models.CharField(max_length=128, verbose_name='Label')),
                ('debit_or_credit', models.IntegerField(choices=[(-1, 'Debit'), (1, 'Credit')], verbose_name='Debit or credit')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount')),
                ('apply_vat', models.BooleanField(default=True, verbose_name='Do apply VAT?')),
                ('vat_to_apply', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='VAT rate')),
                ('apply_provision', models.BooleanField(default=True, verbose_name='Do apply provision?')),
                ('provision_rate', models.DecimalField(blank=True, decimal_places=2, default=40, max_digits=12, verbose_name='Provision rate')),
                ('comment', models.CharField(blank=True, max_length=1024, verbose_name='Comment')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='compta.Account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
            },
        ),
    ]
