# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='all_tax_included',
            field=models.BooleanField(default=True, verbose_name='All tax included'),
        ),
    ]
